"""PersistencePort — abstracts SQL/JSON/whatever from cognition.
Implementations live in server.external."""
from __future__ import annotations
from datetime import datetime
from typing import Optional, Protocol
from server.cognition.contracts import (
    Episode, Fact, Reflection, FeedbackEntry, Reminder,
)


class PersistencePort(Protocol):
    # Episodes
    def save_episode(self, episode: Episode) -> None: ...
    def load_episode(self, episode_id: str) -> Optional[Episode]: ...
    def list_recent_episodes(self, limit: int) -> list[Episode]: ...
    def list_unconsolidated_episodes(self) -> list[Episode]: ...
    def mark_episodes_consolidated(self, episode_ids: list[str], at: datetime) -> None: ...

    # Facts
    def save_fact(self, fact: Fact) -> None: ...
    def find_fact(self, category: str, key: str) -> Optional[Fact]: ...
    def list_active_facts(self) -> list[Fact]: ...
    def invalidate_fact(self, fact_id: str, at: datetime) -> None: ...

    # Identity
    def get_identity_narrative(self) -> Optional[str]: ...
    def save_identity_narrative(self, narrative: str, last_consolidated_at: datetime,
                                last_consolidated_episode_id: Optional[str]) -> None: ...
    def get_last_consolidated_episode_id(self) -> Optional[str]: ...

    # Reflections
    def save_reflection(self, reflection: Reflection) -> None: ...
    def list_recent_reflections(self, limit: int) -> list[Reflection]: ...

    # Feedback
    def save_feedback(self, entry: FeedbackEntry) -> None: ...
    def list_feedback(self, status: Optional[str] = None) -> list[FeedbackEntry]: ...
    def resolve_feedback(self, feedback_id: str) -> None: ...

    # Reminders
    def save_reminder(self, reminder: Reminder) -> None: ...
    def list_pending_reminders(self) -> list[Reminder]: ...
    def update_reminder_status(self, reminder_id: str, status: str) -> None: ...
